The_Cyprus_Project/full stack/webapp/models.py
import sqlalchemy
from datetime import timedelta, datetime
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func



class Articles(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    articles = db.Column(db.String())
    articletitle = db.Column(db.String())
    author = db.Column(db.String(100))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    time = db.Column(db.DateTime)
    

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    user_name = db.Column(db.String(150))
    password = db.Column(db.String(150))
    
#-------------------------------  end of database for blog -------------------------------------


class Whatsapp(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String())
    link = db.Column(db.String())
    institute = db.Column(db.String(100))

The_Cyprus_Project/full stack/webapp/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager, login_manager

db = SQLAlchemy()
DB_NAME = "mywebappdatabase.db"


def create_app():
 app = Flask(__name__)
 app.config["SECRET_KEY"] = "JHHGUIF HUHUH HHUF UH"
 app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///{}".format(DB_NAME)
 db.init_app(app)

 from .views import views
 from .admin import admin


 app.register_blueprint(views, url_prefix="/")
 app.register_blueprint(admin, url_prefix="/")

 from .models import User, Articles
 create_database(app)


 login_manager = LoginManager()
 login_manager.login_view = "admin.login"
 login_manager.init_app(app)

 @login_manager.user_loader
 def load_user(id):
     return User.query.get(int(id))



 return app


def create_database(app):
    if not path.exists("webapp/" + DB_NAME):
        db.create_all(app=app)
        print("Database created!!")

The_Cyprus_Project/full stack/webapp/views.py
from datetime import date, time
from webapp.models import Articles, Whatsapp
from flask import Blueprint, render_template, url_for, request
from flask_login import current_user
from . import db


views = Blueprint("views", __name__)


@views.route("/")
def home():

    # Queries to database to get the post by the 5 most recents

    post = db.session.query(Articles.articles).order_by(
        Articles.date.desc()).limit(5).all()

    post_title = db.session.query(Articles.articletitle).order_by(
        Articles.date.desc()).limit(5).all()

    post_date = db.session.query(Articles.date).order_by(
        Articles.date.desc()).limit(5).all()

    post_author = db.session.query(Articles.author).order_by(
        Articles.date.desc()).limit(5).all()
    post_id = db.session.query(Articles.id).order_by(
        Articles.date.desc()).limit(5).all()

    return render_template("index.html", content=post,  post_title=post_title, post_date=post_date, post_author=post_author, post_id=post_id)


@views.route("/<id>")
def more(id):
    ident = id

    post = Articles.query.get(ident)
    return render_template("more_post.html", content=post)


@views.route("/whatsapp")
def whatsapp():
    if request.method == "POST":
        institute = request.form.get("category")
        category = Whatsapp.query.filter_by(institute=institute).all()
        if category:
            whatsapp = category
            return render_template("whatsapp.html", whatsapp)
    # Queries to database to get All the whatsapp links
    whatsapp_groups = db.session.query(Whatsapp).all()
    return render_template("whatsapp.html", whatsapp=whatsapp_groups)

The_Cyprus_Project/full stack/webapp/templates/admin_login.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Login</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../static/admin.css">
</head>

<body>
   
    <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
<header>
    {% with message = get_flashed_messages() %}
    {% if message %}
    {% for x in message %}
    
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>{{x}}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
     
    {% endfor %}
    {% endif %}
    {% endwith %}

</header>
    <div class="form">
        <div class="form-content">
            <form action="" method="POST">
                <div class="img-icon">
                    <i class="fas fa-user-circle fa-3x"></i>
                </div>
                <div class="form-group">

                    <div class="input-group input">
                        <div class="input-group-addon">
                            <i class="fa fa-user" aria-hidden="true"></i>
                        </div>
                        <input class="form-control" name="username" placeholder="username" type="text" required />
                    </div>
                    <div class="input-group input">
                        <div class="input-group-addon">
                            <i class="fas fa-key"></i>
                        </div>
                        <input class="form-control" name="password" placeholder="password" type="password" required />
                    </div>
                    <div class="submit-btn">
                        <input class="btn btn-success" type="submit" value="Login" />
                    </div>
                </div>
            </form>
        </div>
    </div>



    <script src="" async defer>
    </script>
</body>

</html>

The_Cyprus_Project/full stack/webapp/templates/admin_page.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Admin_panel</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../static/admin_style.css">
</head>

<body>

    <header>
        <nav class="navbar navbar-light bg-light">
            <span class="navbar-brand mb-0 h1">Admin</span>
        </nav>

        {% with message = get_flashed_messages() %}
        {% if message %}
        {% for x in message %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>{{x}}</strong>.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
    </header>
    <h1>Create a Blog Post!</h1>
    <div class="form">
        <form method="POST">
            <div class="form-group">
                <label for="exampleFormControlInput0">section</label>
                <input type="text" class="form-control" id="exampleFormControlInput0" value="Blog" name="section" readonly>
            </div>
            <div class="form-group">
                <label for="exampleFormControlInput1">Title</label>
                <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="Post Title" name="articletitle" required>
            </div>
               <div class="form-group">
               <label for="exampleFormControlInput2">Author</label>
               <input type="text" class="form-control" id="exampleFormControlInput2" placeholder="Author" name="author" required>
            </div>
            <div class="form-group">
                <label for="exampleFormControlTextarea1">Enter Post</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="13" name="articles" required></textarea>
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="Post">
            </div>
        </form>
    </div>
<!-- creating a whatsapp Link -->
<h1>Create Whatsapp links!</h1>
<div class="form">
    <form method="POST">
        <div class="form-group">
            <label for="exampleFormControlInput0">section</label>
            <input type="text" class="form-control" id="exampleFormControlInput0" value="Whatsapp" name="section" readonly>
        </div>
        <div class="form-group">
            <label for="exampleFormControlInput1">Title</label>
            <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="Whatsapp Title"
                name="whatsapp_title" required>
        </div>
        <div class="form-group">
            <label for="exampleFormControlInput2">Link</label>
            <input type="text" class="form-control" id="exampleFormControlInput2" placeholder="Link" name="Whatsapp_link"
                required>
        </div>
        <!-- change category to options instead of input -->
        <div class="form-group">
            <label for="exampleFormControlTextarea1">Category/Institute</label>
            <select class="form-control" id="exampleFormControlTextarea1" name="Institute">
                <option>Easter mediterian</option>
                <option>Near East</option>
                <option>Cyprus International University</option>
                <option>Market Place</option>
                <option>Adverts</option>
                <option>Party</option>
                <option>Church</option>
                <option>Get Together</option>
                <option>Study</option>
            </select>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Post">
        </div>
    </form>

    <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

    <script src="" async defer></script>
</body>

</html>

The_Cyprus_Project/full stack/webapp/templates/index.html
{% extends "base.html" %}
{% block content %} 

<article class="blog">
    <div class="blog-content">
        <div class="col-md-12">

            <h1> {{post_title.0.0}} </h1>

            <p> {{content.0.0}} </p>
            <div class="blog-info">
                <span class="badge badge-secondary"> Date: {{post_date.0.0}}  </span>
                <span class="badge badge-info">Author: {{ post_author.0.0 }}</span>
                <span class="badge badge-primary">Share</span>

            </div>
        </div>

    </div>
</article>

 {% endblock %}

{% block more %}
<!-- Start of blogs mini displays -->
<section class="more-blog-post">
    <h3>More of the latest Stories</h3>
    <div class="content-background">
        <div class="mini-blog">


            <div class="card">
                <h5 class="card-header">Featured</h5>
                <div class="card-body">
                    <h5 class="card-title">{{post_title.1.0}}</h5>
                    <div class="card-text-place">
                    <p class="card-text">{{content.1.0}}</p>
                    </div>
                    <a href={{url_for("views.more", id=post_id.1.0)}} class="btn btn-primary">Read</a>
                </div>
            </div>

            <div class="card">
                <h5 class="card-header">Featured</h5>
                <div class="card-body">
                    <h5 class="card-title">{{post_title.2.0}}</h5>
                    <div class="card-text-place">
                    <p class="card-text">{{content.2.0}}</p>
                    </div>
                    <a href={{url_for("views.more", id=post_id.2.0)}} class="btn btn-primary">Read</a>
                </div>
            </div>

            <div class="card">
                <h5 class="card-header">Featured</h5>
                <div class="card-body">
                    <h5 class="card-title">{{post_title.3.0}}</h5>
                    <div class="card-text-place">
                    <p class="card-text">{{content.3.0}}</p>
                    </div>
                    <a href={{url_for("views.more", id=post_id.3.0)}} class="btn btn-primary">Read</a>
                </div>
            </div>




        </div>
    </div>
</section>
{% endblock %}
<!-- End of blogs mini displays -->

The_Cyprus_Project/full stack/webapp/templates/more_post.html
{% extends "base.html" %}
{% block content %}


    <article class="blog">
        <div class="blog-content">
            <div class="col-md-12">
    
                <h1> {{content.articletitle}} </h1>
    
                <p> {{content.articles}} </p>
                <div class="blog-info">
                    <span class="badge badge-secondary"> Date: {{content.date}} </span>
                    <span class="badge badge-info">Author: {{ content.author }}</span>
                    <span class="badge badge-primary">Share</span>
    
                </div>
            </div>
    
        </div>
    </article>


{% endblock %}

The_Cyprus_Project/full stack/webapp/templates/whatsapp.html
{% extends "base.html" %}
{% block content %}



<div class="wa-search-bg">
    <div class="wa-search">
    <form method="post">
        <div class="form-group">
            <label for="exampleFormControlSelect1">Filter By</label>
            <select class="form-control" id="exampleFormControlSelect1" name="category">
                <option>Easter mediterian</option>
                <option>Near East</option>
                <option>Cyprus International University</option>
                <option>Market Place</option>
                <option>Adverts</option>
                <option>Party</option>
                <option>Church</option>
                <option>Get Together</option>
                <option>Study</option>
            </select>
            <input type="submit" class="btn btn-secondary" value="Search">
        </div>
     
    </form>
    </div>
</div>

<div class="whatsapp">
    {% if whatsapp %}
    {% for x in whatsapp %}
    <div class="wa-bg">
        <div class="wa"> 
           <div class="wa-head"><h3>{{x.name}}</h3></div> 
           <a href="" target="_blank" rel="noopener noreferrer">lINK TO A WHATS APP GROUP HERE</a>
        </div>
    </div>
    {% endfor%}
    {% endif %}
    {% if not whatsapp %}
</div>

{% endblock %}